name: Notify Discord

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          details: A new pull request is awaiting approval to initiate the creation of a NuGet package for ${{ inputs.project_name }}.
          webhookurl: ${{ secrets.DISCORD_WEBHOOK }}
