name: Notify Discord

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          details: ${{ inputs.message }}
          webhookurl: ${{ secrets.DISCORD_WEBHOOK }}
