name: Notify Discord

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          details: |
          A new release for ${{ inputs.project_name }} is awaiting approval before the NuGet package can be created. 
          🔗 [Click here to review and approve the action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          webhookurl: ${{ secrets.DISCORD_WEBHOOK }}
