name: NuGet Publish

# Variables
on:
  workflow_call:
    inputs:
      dotnet_version:
        required: false
        type: string
        default: '9.0.x'
      project_name:
        type: string
        required: true
      project_path:
        required: false
        type: string
        default: './'
      need_run_test:
        required: false
        type: boolean
        default: true
    secrets:
      NUGET_APIKEY:
        required: true
      DISCORD_WEBHOOK:
        required: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:

  # Create the NuGet package
  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

    # Install .NET 9.0 SDK
    - name: Setup .NET ${{ inputs.dotnet_version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }} # Use a specific version or '9.0.x' for the latest 9.0 preview

    # Build the NuGet package in the folder from the environment variable NuGetDirectory
    - name: Build
      run: dotnet build ${{ inputs.project_path }} --configuration Release
      
    # Create the NuGet package in the folder from the environment variable NuGetDirectory
    - name: Pack
      run: dotnet pack ${{ inputs.project_path }} --configuration Release --output ${{ env.NuGetDirectory }} --include-symbols --include-source

    # Publish the NuGet package as an artifact, so they can be used in the following jobs
    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg

  # Run Tests if needed
  call_run_test:
    uses: SkJonko/Centralized-Workflow-YAMLs/.github/workflows/run-test.yaml@main
    with:
      need_run_test: ${{ inputs.need_run_test }}


  # Validate the NuGet package
  call_validate_nuget:
     needs: [ create_nuget, call_run_test ]
     uses: SkJonko/Centralized-Workflow-YAMLs/.github/workflows/validate-nuget.yaml@main
     with:
       dotnet_version: ${{ inputs.dotnet_version }}


  # Call Notify Discord.
  # This will inform that new PR is available and needs approval for PROD
  call_notify_discord:
    if: github.event_name == 'Release'
    needs: [ call_validate_nuget ]
    uses: SkJonko/Centralized-Workflow-YAMLs/.github/workflows/notify-discord.yaml@main
    with:
      project_name: ${{ inputs.project_name }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
           
      
  # Call Deploy to NuGet.org
  call_deploy:
    if: github.event_name == 'Release'
    needs: [ call_validate_nuget ]
    uses: SkJonko/Centralized-Workflow-YAMLs/.github/workflows/deploy-nuget.yaml@main
    with:
      dotnet_version: ${{ inputs.dotnet_version }}
    secrets:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
