name: Run Tests

on:
  workflow_call:
    inputs:
      need_run_test:
        required: false
        type: boolean
        default: true
      dotnet_version:
        required: false
        type: string
        default: '9.0.x'

jobs:
  run_test:
    if: ${{ inputs.need_run_test == true }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET ${{ inputs.dotnet_version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Find Test Project
      id: find_test_project
      run: |
        project_path=$(find . -type f -name '*Test.csproj' | head -n 1)
        if [ -z "$project_path" ]; then
          echo "❌ No *Test.csproj file found!"
          exit 1
        fi
        echo "✅ Found test project: $project_path"
        echo "project_path=$project_path" >> $GITHUB_OUTPUT

    - name: Install coverlet collector (if needed)
      run: dotnet add "${{ steps.find_test_project.outputs.project_path }}" package coverlet.collector

    - name: Run Tests with Coverage
      run: dotnet test "${{ steps.find_test_project.outputs.project_path }}" --configuration Release --collect:"XPlat Code Coverage"

    - name: Convert coverage to lcov (optional, for prettier visualization)
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:"HtmlInline_AzurePipelines;Cobertura"


    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coveragereport

    # Optional: Upload to GitHub summary (Actions UI)
    - name: Publish Coverage Summary
      run: |
        echo "## Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
        echo "[View Coverage Report](./coveragereport/index.html)" >> $GITHUB_STEP_SUMMARY

  run_test_skipped:
    if: ${{ inputs.need_run_test != true }}
    runs-on: ubuntu-latest
    outputs:
      test_status: success
    steps:
      - name: Skipping tests
        run: echo "Tests are disabled via input"
